const secret = "kd-bootstrap-20260806";
const out = (body, status=200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json", "cache-control": "no-store" } });
async function run(request) {
  if (request.method !== "POST" || request.headers.get("x-bootstrap-secret") !== secret) return out({error:"NOT_FOUND"},404);
  const base=process.env.SUPABASE_URL.replace(/\/$/,""); const key=process.env.SUPABASE_SERVICE_ROLE_KEY; const h={apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json"};
  const call=async(path,o={})=>{const r=await fetch(base+path,{...o,headers:{...h,...(o.headers||{})}});const d=await r.json().catch(()=>null);if(!r.ok)throw Error(path+" "+r.status+" "+JSON.stringify(d));return d;};
  try { const email="admin@king-design.local"; let d=await call("/auth/v1/admin/users?email="+encodeURIComponent(email)); let u=d?.users?.[0]||d?.[0]; if(!u) u=await call("/auth/v1/admin/users",{method:"POST",body:JSON.stringify({email,password:"admin123",email_confirm:true,user_metadata:{display_name:"管理员"}})}); else u=await call("/auth/v1/admin/users/"+u.id,{method:"PUT",body:JSON.stringify({password:"admin123",email_confirm:true})}); let o=await call("/rest/v1/organizations?select=id&limit=1"); let oid=o?.[0]?.id; if(!oid) oid=(await call("/rest/v1/organizations",{method:"POST",headers:{prefer:"return=representation"},body:JSON.stringify({name:"KiNG DESiGN"})}))[0].id; await call("/rest/v1/memberships",{method:"POST",headers:{prefer:"resolution=merge-duplicates"},body:JSON.stringify({user_id:u.id,organization_id:oid,role:"admin"})}); return out({ok:true}); } catch(e){return out({error:"BOOTSTRAP_FAILED",detail:String(e.message)},500);}
}
export default async function handler(req,res){if(!res)return run(req);const chunks=[];for await(const c of req)chunks.push(c);const r=await run(new Request(`https://${req.headers.host}${req.url}`,{method:req.method,headers:req.headers,body:Buffer.concat(chunks)}));r.headers.forEach((v,k)=>res.setHeader(k,v));res.statusCode=r.status;res.end(Buffer.from(await r.arrayBuffer()));}
